project:
  type: website
  resources:
    - "*.pdf"

website:
  title: "Sergio Garcia Busto"
  repo-url: https://github.com/sgb67/sgb67.github.io
  repo-actions: [source, issue]
  open-graph:
    locale: en_US
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - projects.qmd
      - comms.qmd
      - blog.qmd

format:
  html:
    theme: brite
    css: styles.css



