project:
  type: website
  resources:
    - "*.pdf"

website:
  title: "Sergio Garcia Busto"
  twitter-card:
    creator: "@sergiogarciabus"
  open-graph:
    locale: en_US
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - projects.qmd
      - skills.qmd

format:
  html:
    theme: brite
    css: styles.css



